In [2]:
import numpy as np
import cv2
import networkx as nx 
import matplotlib.pyplot as plt
import os
import time
import pandas as pd


In [6]:
def for_index_finding(n_u, n_v):
    if len(n_u) != len(n_v):
        print("The length of n_u and n_v are not equal")
        return 0, 0, 0, 0, 0
    else:
        product_val = n_u * n_v
        sum_val = n_u + n_v
        sz_index = np.sum(product_val)
        PI_index = np.sum(sum_val)
        ABC_index = np.sum(np.sqrt((sum_val - 2) / product_val))
        NGG_index = np.sum(1/np.sqrt(product_val))
        Mo_index = np.sum(np.abs(n_u - n_v))
        return sz_index, PI_index, ABC_index, NGG_index, Mo_index


In [7]:
def file_reader(file_path):
    with open(file_path) as f:
        array_neigh = [x for x in f.read().split('\n')]
        print(len(array_neigh))
    return array_neigh

In [8]:
def index_array_creator(outer_file_path):
    n_v_path = os.path.join(outer_file_path, "neigh_v_val.txt")
    n_u_path = os.path.join(outer_file_path, "neigh_u_val.txt")
    n_u_whole_class = file_reader(n_u_path)
    n_v_whole_class = file_reader(n_v_path)
    indices = []
    for i in range(len(n_u_whole_class) - 1):
        try:
            val1 = np.array([int(x) for x in n_u_whole_class[i][1:-1].split(",")])
            val2 = np.array([int(x) for x in n_v_whole_class[i][1:-1].split(",")])        
        except:
            print("Error in line: ", i)  
            break 
        indices.append(for_index_finding(val1, val2))

    return indices
    # return None

In [40]:
file_path = "Alzheimers_graph_valued_Dataset 2/test/NonDemented"

In [41]:
index_arrays = index_array_creator(file_path)
df = pd.DataFrame(index_arrays, columns=["sz_index", "PI_index", "ABC_index", "NGG_index", "Mo_index"])

641
641


In [42]:
df.to_csv(os.path.join(file_path, "index_values.csv"))

In [3]:
def find_file_in_folders(root_folder, target_file_name):
    index_value = None
    vsl_check = 0
    demented_class = {'NonDemented': 0, 'VeryMildDemented': 1, 'MildDemented': 2, 'ModerateDemented': 3}
    for folder_path, _, files in os.walk(root_folder):
        # print(type(files))
        if target_file_name in files:
            demented_class_key = str(folder_path).split('/')[-1]
            print(str(folder_path).split('/')[-1])
            index_value_creator = pd.read_csv(os.path.join(folder_path, target_file_name))
            index_value_creator = pd.DataFrame(index_value_creator)
            index_value_creator["demented_class"] = demented_class[demented_class_key]
            if vsl_check == 0:
                index_value = index_value_creator
                vsl_check += 1
            else:
                index_value = pd.concat([index_value, index_value_creator], ignore_index=True)
            # return os.path.join(folder_path, target_file_name)
    
    return index_value

root_folder = "Alzheimers_graph_valued_Dataset 2/test"
root_folder2 = "Alzheimers_graph_valued_Dataset 2/train"
target_file_name = "values_of_index_with_weiner.csv"

found_file_path = find_file_in_folders(root_folder, target_file_name)
found_file_path2 = find_file_in_folders(root_folder2, target_file_name)


# if found_file_path:
#     print(f"File '{target_file_name}' found at: {found_file_path}")
# else:
#     print(f"File '{target_file_name}' not found in the specified folder and its subfolders.")


VeryMildDemented
ModerateDemented
MildDemented
NonDemented
VeryMildDemented
ModerateDemented
MildDemented
NonDemented


In [4]:
found_file_path = found_file_path.drop('Unnamed: 0', axis=1)

In [5]:
found_file_path

sz_index  PI_index      ABC_index     NGG_index  Mo_index  \
0     1304815186  57911108  120883.350403  18052.719739  46125198   
1     1306300073  57990072  120641.792534  17897.077956  46091882   
2     1230151070  57677556  124904.286807  19026.916574  46456434   
3     1217454058  57516662  122336.822350  18280.796249  46393670   
4     1258011469  57762370  124602.458480  18920.753658  46291068   
...          ...       ...            ...           ...       ...   
1274  1351360980  57838924  119438.062089  17820.070232  45546664   
1275  1320366232  57908162  121851.397973  18274.503190  45846974   
1276  1350220177  58066754  122302.248292  18279.228172  45687670   
1277  1315594225  57692000  123089.733644  18796.371308  45660088   
1278  1291605828  57805796  121977.016376  18184.491328  46211114   

      Weiner_index  demented_class  
0         449993.0               1  
1         450884.0               1  
2         448340.0               1  
3         451633.0               1  
4         448220.0               1  
...            ...             ...  
1274      450351.0               0  
1275      449027.0               0  
1276      449348.0               0  
1277      448533.0               0  
1278      450224.0               0  

[1279 rows x 7 columns]

In [7]:
found_file_path2 = found_file_path2.drop('Unnamed: 0', axis=1)

In [8]:
found_file_path2

sz_index  PI_index      ABC_index     NGG_index  Mo_index  \
0     1662733933  57244882  109244.560766  14882.749103  42392484   
1     1474845141  56961578  107565.004454  14556.652724  43983088   
2     1395582348  57495610  110068.315189  15098.908601  45153564   
3     1472372892  57643830  108498.751308  14820.421215  44614250   
4     1464946622  57932518  113511.009240  16030.034919  44659666   
...          ...       ...            ...           ...       ...   
5116  1556636152  57546284  110106.664783  14895.121465  43699248   
5117  1546999154  57750324  107770.298764  14607.253905  44242824   
5118  1403678485  56396266  108253.461386  14596.824977  43882742   
5119  1387621874  57848268  114225.350502  15959.231318  45378116   
5120  1578366387  57646190  105653.791018  14265.088892  44037370   

      Weiner_index  demented_class  
0         453084.0               1  
1         458569.0               1  
2         453981.0               1  
3         454267.0               1  
4         450756.0               1  
...            ...             ...  
5116      453118.0               0  
5117      452453.0               0  
5118      460198.0               0  
5119      451142.0               0  
5120      455470.0               0  

[5121 rows x 7 columns]

In [11]:
found_file_path2.to_csv("/Users/gnbhavithran/Python_github/brain_graph_final_only/Alzheimers_graph_valued_Dataset 2/train_dataset_all_demented_index_values_with_weiner.csv")

In [5]:
import numpy as np
import math

A = (3, 4)
math.prod(A)

12

In [2]:
import numpy as np

# Create a sample matrix
matrix = np.array([[1.2, 3.4, 0.5],
                   [0.9, 2.1, 4.5],
                   [2.3, 1.0, 0.8]])

# Define the threshold value
threshold = 2.0

# Apply the threshold using NumPy's broadcasting
thresholded_matrix = np.where(matrix < threshold, 0,  1)

print(thresholded_matrix)


[[0 1 0]
 [0 1 1]
 [1 0 0]]


In [3]:
isinstance(thresholded_matrix, np.ndarray)

True

In [ ]:
import os
import pandas as pd
import numpy as np

h = np.loadtxt()